name: Run Tests and Generate Report

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt update && sudo apt install -y default-jdk
          curl -o allure-2.23.0.tgz -L https://github.com/allure-framework/allure2/releases/download/2.23.0/allure-2.23.0.tgz
          tar -xzf allure-2.23.0.tgz
          sudo mv allure-2.23.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Run Pytest and Generate Allure Raw Data
        run: |
          pytest tests/main.py --alluredir=temps

      - name: Generate Allure HTML Report
        run: |
          allure generate temps -o report --clean

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: report
